version: '2.0'
services:
  web:
    build: ./config/nginx
    image: nginx:1.0
    ports:
      - '80'
    links:
      - app
  app:
    build: .
    image: ror:1.0
    links:
      - db
# web:
#   build: ./config/nginx
#   ports:
#     - '80'
#   links:
#     - app
# app:
#   build: .
#   links:
#     - db
  db:
    image: mysql:5.6.22
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root